  mysql_root_password: devops
  mysql_databases:
    - name: devopsdemo
      encoding: latin1
      collation: latin1_general_ci
  mysql_users:
    - name: devops
      host: "%"
      password: devops
      priv: "devopsdemo.*:ALL"
  mysql_bind_address: '0.0.0.0'